---
- name: Deploy database infrastructure
  hosts: db
  become: true
  roles:
    - database

- name: Deploy DNS infrastructure
  hosts: dns
  become: true
  roles:
    - dns_config

- name: Deploy web server infrastructure
  hosts: web
  become: true
  roles:
    - webserver
    - app_deployment
    - firewall
    - users

