- name: Install DNS server
  apt:
    name: bind9
    state: present
  become: true

- name: Configure named.conf
  copy:
    src: files/named.conf  # Ensure the path is correct
    dest: /etc/bind/named.conf
  notify:
    - Restart DNS

- name: Start and enable DNS service
  service:
    name: bind9
    state: started
    enabled: true
  become: true

