# Ensure UFW is installed (instead of firewalld)
- name: Install UFW
  apt:
    name: ufw
    state: present
  become: true

# Enable UFW
- name: Enable UFW
  command: ufw --force enable
  become: true

# Allow HTTP and HTTPS through UFW
- name: Allow HTTP and HTTPS through UFW
  ufw:
    rule: allow
    name: "{{ item }}"
  loop:
    - 'Apache'          # This allows HTTP (Port 80)
    - 'Apache Secure'   # This allows HTTPS (Port 443)
  become: true

# Allow MySQL through UFW using port 3306
- name: Allow MySQL through UFW
  ufw:
    rule: allow
    port: '3306'
    proto: tcp
  become: true

# Reload UFW to apply changes
- name: Reload UFW
  command: ufw reload
  become: true

